FROM node:alpine

WORKDIR /app

COPY package.json .
RUN npm install

# Copy all source code if required.
# Skipping now since we're using docker volumes in the docker-compose file
COPY . .

CMD ["npm", "run", "start"]